name: template
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  accordion: ^2.6.0
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dio: ^5.2.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.2
  easy_stepper: ^0.8.0
  fl_chart: ^0.60.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_breadcrumb: ^1.0.1
  fluttertoast: ^8.0.0
  image_picker: ^1.0.0
  modal_bottom_sheet: ^3.0.0-pre
  open_file: any
  path_provider: any
  sizer: 2.0.14

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splashLogo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/constants/languages/
    - assets/images/
  fonts:
    - family: Sukar
      fonts:
        - asset: assets/fonts/Sukar_black.ttf
    - family: Riyal
      fonts:
        - asset: assets/fonts/riyal.otf
